version: '3.8'
services:
  db:
    image: postgres:15
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: ./services/api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET: ${STRIPE_SECRET}
    ports:
      - "4000:4000"
    volumes:
      - ./services/api/src:/app/src
      - ./services/api/prisma:/app/prisma
    command: npm run dev

  web:
    build: ./services/web
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
    - ./services/web/src:/app/src
    - ./services/web/vite.config.js:/app/vite.config.js
    - ./services/web/index.html:/app/index.html
    command: npm run dev
  
  admin:
    build: ./services/admin
    depends_on:
      - api
    ports:
      - "5000:5000"
    volumes:
    - ./services/admin/src:/app/src
    - ./services/admin/vite.config.js:/app/vite.config.js
    - ./services/admin/index.html:/app/index.html
    command: npm run dev

volumes:
  db_data: